### ISSUE TITLE
Create a faucet for HOPR token

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-ethereum#28]
simple webpage with a simple button "give me hopr tokens"

- [x] `hopr-ethereum` API should contain contract addresses
- [x] `hopr-core-ethereum` should use `hopr-ethereum` API to get the contract addresses
- [x] implement faucet in `hopr-ethereum`

**Comment by bitcoinmeetups** [comment]
Can I test this website and receive some HOPR tokens in return?

**Comment by jjperezaguinaga** [comment]
@bitcoinmeetups The faucet is currently focused on the development testnet, which isn't live yet. The faucet will issue HOPR tokens with no value other than for development purposes.

**Comment by jjperezaguinaga** [comment]
Removing milestone on this one until we get back to HOPR tokens.
